stages:
  - setup
  - test

variables:
  PHP_VERSION: "8.2"

setup:
  stage: setup
  script:
    - apt-get update && apt-get install -y unzip git curl libzip-dev
    - docker-php-ext-install zip
    - cp .env.test.local .env
    - composer install

test:
  stage: test
  script:
    - vendor/bin/phpunit --configuration phpunit.xml
  artifacts:
    when: always
    paths:
      - coverage/
    reports:
      junit: junit.xml

default:
  before_script:
    - apt-get update && apt-get install -y unzip git curl libzip-dev
    - docker-php-ext-install zip

job:
  script:
    - cp .env.test .env.test.local
    - composer install
    - vendor/bin/phpunit --configuration phpunit.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
